name: 'My Custom Action'
description: 'This action prints a message'
runs:
  using: 'composite'
  steps:
    - run: |
        echo "Hello from the custom action!"
        echo "out='true'" >> $GITHUB_OUTPUT
      shell: bash
