name: Code Sanity
on:
    pull_request
jobs:
    # linter:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v3
    #         - name: Run go linter
    #           uses: golangci/golangci-lint-action@v3
    #           with: 
    #             version: v1.54.2
    #             # args: |
    #                 # $(git diff --name-only ${{ github.event.pull_request.head.sha }} ${{ github.sha }} | grep '\.go$')
    coverage:
        runs-on: ubuntu-latest
        env:
            CURRENT_BRANCH: ${{ github.head_ref }}
            TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0  # Ensure the entire history is fetched
            - name: Debug Branch Names
              run: |
                echo "Current branch: ${{ github.head_ref }}"
                echo "Target branch: ${{ github.base_ref }}"
        
            - name: Print Changed Files
              run: |
                git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
                git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }}
                # - name: Run coverage
            #   run: make sanity;