name: Code Sanity
on:
    pull_request
jobs:
    # linter:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v3
    #         - name: Run go linter
    #           uses: golangci/golangci-lint-action@v3
    #           with: 
    #             version: v1.54.2
    #             # args: |
    #                 # $(git diff --name-only ${{ github.event.pull_request.head.sha }} ${{ github.sha }} | grep '\.go$')
    coverage:
        runs-on: ubuntu-latest
        env:
            CURRENT_BRANCH: ${{ github.head_ref }}
            TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0  # Ensure the entire history is fetched
            - name: Get changes
              run: | 
                make prep-coverage
                git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '.go' > ./coverage/changed_files.txt
                cat ./coverage/changed_files.txt
            - name: Run coverage
              run: make sanity
