name: 'Helper Workflow'
on: workflow_call
jobs:
  just-a-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Random log
        run: |
          echo "Inside helper workflow"
