name: Linting
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
jobs:
    linter:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Run go linter
              run: echo "Test"
            #  uses: golangci/golangci-lint-action@v3
              #with: 
              #  version: v1.54.2
                # args: |
                    # $(git diff --name-only ${{ github.event.pull_request.head.sha }} ${{ github.sha }} | grep '\.go$')
